### PR TITLE
git ls-files -z -- .coveragerc | xargs -0 sed -i '/ \*\/tmp\*/d'

### PR DESCRIPTION
**Pull request by asottile**
Committed via https://github.com/asottile/all-repos

### CODE REVIEW

**Comment by asottile** [comment]
this was unfortunate copy paste, it came from some `.coveragerc` I wrote years ago for some specific reason that I can't actually track down -- I've purged this same line from all of my projects and had no problems.

The failures here will be solved by the second commit in #14

**Comment by asottile** [comment]
I'll rebase

**Comment by asottile** [comment]
oh er uh merge works too 🎉

**Comment by ArnaudBrousseau** [comment]
No need, let's merge this

**Comment by ArnaudBrousseau** [comment]
👍

**Pull request merged**
