### PR TITLE
Test against python3.5

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by ArnaudBrousseau** [comment]
Can you add "py35 support" to the "Unreleased" section of the CHANGELOG? Otherwise, :shipit:

**Comment by asottile** [comment]
Why changelog when you have git history and github releases?

**Comment by ArnaudBrousseau** [comment]
Changelog is a standard practice. git logs can be hard to make sense of.

I'm currently not making use of Github's releases. Just git tag. Could switch to using that instead of CHANGELOG but for now let's stick to that. I'll delete the Changelog when I actually start using GH releases.

**Comment by asottile** [comment]
This also doesn't make any end-user changes, just testing infrastructure so it shouldn't belong in a changelog or release notes

**Comment by ArnaudBrousseau** [comment]
Fair enough!

🚀

**Pull request merged**
